### ISSUE TITLE
Traceback (most recent call last):   File "H:\Anaconda\lib\multiprocessing\process.py", line 297, in _bootstrap     self.run()   File "H:\Anaconda\lib\multiprocessing\process.py", line 99, in run     self._target(*self._args, **self._kwargs)   File "H:\Anaconda\lib\multiprocessing\pool.py", line 110, in worker     task = get()   File "H:\Anaconda\lib\multiprocessing\queues.py", line 354, in get     return _ForkingPickler.loads(res) AttributeError: Can't get attribute 'cut_pickle' on <module '__mp_main__' from 'H:\\GaitCode\\pretreatment.py'>

### ISSUE THREAD

**Issue by sjhsn** [AbnerHqC/GaitSet#102]
https://github.com/AbnerHqC/GaitSet/blob/14ee4e67e39373cbb9c631d08afceaf3a23b72ce/pretreatment.py#L120

**Comment by sjhsn** [comment]
Can't get attribute 'cut_pickle' on <module '__mp_main__' from 'H:\\GaitCode\\pretreatment.py'>
please guide me

**Comment by m2005dh** [comment]
hi, you may need to Install numpy 1.16.2
