### ISSUE TITLE
关于train.py报错的问题

### ISSUE THREAD

**Issue by whb1820127194** [AbnerHqC/GaitSet#107]
大佬你好，我在跑train.py代码的时候碰到下面的问题
(pytorch) aistudio@jupyter-115969-346818:~/work/gait$ python train.py
Initialzing...
Initializing data source...
Loading training data...
Traceback (most recent call last):
  File "train.py", line 18, in <module>
    m = initialization(conf, train=opt.cache)[0]
  File "/home/aistudio/work/gait/model/initialization.py", line 57, in initialization
    train_source, test_source = initialize_data(config, train, test)
  File "/home/aistudio/work/gait/model/initialization.py", line 18, in initialize_data
    train_source.load_all_data()
  File "/home/aistudio/work/gait/model/utils/data_set.py", line 45, in load_all_data
    self.load_data(i)
  File "/home/aistudio/work/gait/model/utils/data_set.py", line 48, in load_data
    return self.__getitem__(index)
  File "/home/aistudio/work/gait/model/utils/data_set.py", line 62, in __getitem__
    data = [self.__loader__(_path) for _path in self.seq_dir[index]]
  File "/home/aistudio/work/gait/model/utils/data_set.py", line 62, in <listcomp>
    data = [self.__loader__(_path) for _path in self.seq_dir[index]]
  File "/home/aistudio/work/gait/model/utils/data_set.py", line 52, in __loader__
    path)[:, :, self.cut_padding:-self.cut_padding].astype(
  File "/home/aistudio/work/gait/model/utils/data_set.py", line 85, in img2xarray
    dims=['frame', 'img_y', 'img_x'],
  File "/home/aistudio/work/anaconda3/envs/pytorch/lib/python3.6/site-packages/xarray/core/dataarray.py", line 368, in __init__
    coords, dims = _infer_coords_and_dims(data.shape, coords, dims)
  File "/home/aistudio/work/anaconda3/envs/pytorch/lib/python3.6/site-packages/xarray/core/dataarray.py", line 120, in _infer_coords_and_dims
    "and dims: %s vs %s" % (len(shape), len(dims))
ValueError: different number of dimensions on data and dims: 1 vs 3
不太清楚是哪里出了问题，望解惑

**Comment by heheli1998** [comment]
请问您解决了吗，我也是遇到了这个问题

**Comment by heheli1998** [comment]
您好，请问这个问题您解决了吗

**Comment by sweetwaterrain** [comment]
我也是这个问题，请问解决了吗
