### ISSUE TITLE
win10 train错误

### ISSUE THREAD

**Issue by TiNMad11** [AbnerHqC/GaitSet#109]
ValueError: cannot reshape array of size 230400 into shape (64,64,newaxis)

**Comment by TiNMad11** [comment]
C:\Users\TiNMad\Anaconda3\python.exe "F:/pycharm/PyCharm 2019.3.3/GaitSet-master/GaitSet/train.py"
Initialzing...
Initializing data source...
Loading training data...
Traceback (most recent call last):
  File "F:/pycharm/PyCharm 2019.3.3/GaitSet-master/GaitSet/train.py", line 18, in <module>
    m = initialization(conf, train=opt.cache)[0]
  File "F:\pycharm\PyCharm 2019.3.3\GaitSet-master\GaitSet\model\initialization.py", line 57, in initialization
    train_source, test_source = initialize_data(config, train, test)
  File "F:\pycharm\PyCharm 2019.3.3\GaitSet-master\GaitSet\model\initialization.py", line 18, in initialize_data
    train_source.load_all_data()
  File "F:\pycharm\PyCharm 2019.3.3\GaitSet-master\GaitSet\model\utils\data_set.py", line 45, in load_all_data
    self.load_data(i)
  File "F:\pycharm\PyCharm 2019.3.3\GaitSet-master\GaitSet\model\utils\data_set.py", line 48, in load_data
    return self.__getitem__(index)
  File "F:\pycharm\PyCharm 2019.3.3\GaitSet-master\GaitSet\model\utils\data_set.py", line 62, in __getitem__
    data = [self.__loader__(_path) for _path in self.seq_dir[index]]
  File "F:\pycharm\PyCharm 2019.3.3\GaitSet-master\GaitSet\model\utils\data_set.py", line 62, in <listcomp>
    data = [self.__loader__(_path) for _path in self.seq_dir[index]]
  File "F:\pycharm\PyCharm 2019.3.3\GaitSet-master\GaitSet\model\utils\data_set.py", line 52, in __loader__
    path)[:, :, self.cut_padding:-self.cut_padding].astype(
  File "F:\pycharm\PyCharm 2019.3.3\GaitSet-master\GaitSet\model\utils\data_set.py", line 79, in img2xarray
    for _img_path in imgs
  File "F:\pycharm\PyCharm 2019.3.3\GaitSet-master\GaitSet\model\utils\data_set.py", line 80, in <listcomp>
    if osp.isfile(osp.join(flie_path, _img_path))]
  File "C:\Users\TiNMad\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py", line 292, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "C:\Users\TiNMad\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py", line 56, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: cannot reshape array of size 230400 into shape (64,64,newaxis)

Process finished with exit code 1

**Comment by weilanhanf** [comment]
you may need to change your dataset_path after pertreatment

**Comment by m2005dh** [comment]
Hi, @AbnerHqC  @wuangkun 
@TiNMad11 Did you solve it?
@weilanhanf What do you mean by changing the dataset_path? if you mean in config.py I did that but I got same error again.

conf = {
    "WORK_PATH": "./work",
    "CUDA_VISIBLE_DEVICES": "0,1",
    "data": {
        'dataset_path': "E:\Gait\GaitSet\GaitSet-master\output",
        'resolution': '64',
        'dataset': 'CASIA-B',
        # In CASIA-B, data of subject #5 is incomplete.
        # Thus, we ignore it in training.
        # For more detail, please refer to
        # function: utils.data_loader.load_data
        'pid_num': 73,
        'pid_shuffle': False,
    },
    "model": {
        'hidden_dim': 256,
        'lr': 1e-4,
        'hard_or_full_trip': 'full',
        'batch_size': (8, 16),
        'restore_iter': 0,
        'total_iter': 80000,
        'margin': 0.2,
        'num_workers': 3,
        'frame_num': 30,
        'model_name': 'GaitSet',
    },
}

**Comment by wyp196** [comment]
解决了吗，楼主

**Comment by m2005dh** [comment]
Sorry, but I still get the same error.
Could you please explain more and also give me more information about the version of modules that you used in your project?

> 解决了吗，楼主
