### ISSUE TITLE
RuntimeError: cannot perform reduction function

### ISSUE THREAD

**Issue by jiangSeu** [AbnerHqC/GaitSet#122]
Training START
into model/fit
Traceback (most recent call last):
  File "train.py", line 21, in <module>
    m.fit()
  File "/home/caodongjiang/gait/gaitSet-master/model/model.py", line 174, in fit
    ) = self.triplet_loss(triplet_feature, triplet_label)
  File "/home/caodongjiang/anaconda3/envs/gaitSet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/caodongjiang/anaconda3/envs/gaitSet/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 152, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/caodongjiang/anaconda3/envs/gaitSet/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 162, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/caodongjiang/anaconda3/envs/gaitSet/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 83, in parallel_apply
    raise output
  File "/home/caodongjiang/anaconda3/envs/gaitSet/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 59, in _worker
    output = module(*input, **kwargs)
  File "/home/caodongjiang/anaconda3/envs/gaitSet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/caodongjiang/gait/gaitSet-master/model/network/triplet.py", line 23, in forward
    hard_hn_dist = torch.min(torch.masked_select(dist, hn_mask).view(n, m, -1), 2)[0]
**RuntimeError: cannot perform reduction function min on tensor with no elements because the operation does not have an identity**

**Comment by chenchenver** [comment]
请问你解决了吗  我也遇到相同的问题

**Comment by jiangSeu** [comment]
> 请问你解决了吗 我也遇到相同的问题

还没有 加个好友沟通一下？qq：1187714583

**Comment by hhhhhhogan** [comment]
> > 请问你解决了吗 我也遇到相同的问题
> 
> 还没有 加个好友沟通一下？qq：1187714583

你好，qq加不了了，请问怎么联系呢
