### ISSUE TITLE
OU-MVLP数据预处理

### ISSUE THREAD

**Issue by BoNiu-HZY** [AbnerHqC/GaitSet#146]
@@OU-MVLP原始数据集预处理中途出现了下面的类型错误，可能是什么原因造成的，有人能解决吗？@AbnerHqC

# JOB 32000 : --START-- Silhouette_015-01-06105
# JOB 32000 : --FINISH-- Contain 52 valid frames. Saved to D:\DataSet\pretreatment\OU-MVLP\Silhouette_015-01\06105.
# JOB 32500 : --START-- Silhouette_015-01-06629
# JOB 32500 : --FINISH-- Contain 72 valid frames. Saved to D:\DataSet\pretreatment\OU-MVLP\Silhouette_015-01\06629.
# JOB 33000 : --START-- Silhouette_015-01-07165
# JOB 33000 : --FINISH-- Contain 52 valid frames. Saved to D:\DataSet\pretreatment\OU-MVLP\Silhouette_015-01\07165.

ERROR OCCUR: PID ##%d##, ERRORTYPE: %s

 8745 <class 'TypeError'>
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "D:\anaconda3\envs\aaa\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "D:\代码复现\GaitSet_cpu_source\pretreatment.py", line 130, in cut_pickle
    img = cv2.imread(frame_path)[:, :, 0]
TypeError: 'NoneType' object is not subscriptable
"""

**Comment by w1998w** [comment]
我当时遇到过这个问题，我一般再重新运行一下 把之前处理的原图片删掉，继续裁剪没处理过的就可以了

**Comment by zhang123-sys** [comment]
OU-MVLP数据预处理，源数据要按subject id->view 排，下载按view 0,30度下载的

> @@OU-MVLP原始数据集预处理中途出现了下面的类型错误，可能是什么原因造成的，有人能解决吗？@AbnerHqC
> 
> # JOB 32000 : --START-- Silhouette_015-01-06105
> # JOB 32000 : --FINISH-- Contain 52 valid frames. Saved to D:\DataSet\pretreatment\OU-MVLP\Silhouette_015-01\06105.
> # JOB 32500 : --START-- Silhouette_015-01-06629
> # JOB 32500 : --FINISH-- Contain 72 valid frames. Saved to D:\DataSet\pretreatment\OU-MVLP\Silhouette_015-01\06629.
> # JOB 33000 : --START-- Silhouette_015-01-07165
> # JOB 33000 : --FINISH-- Contain 52 valid frames. Saved to D:\DataSet\pretreatment\OU-MVLP\Silhouette_015-01\07165.
> ERROR OCCUR: PID ##%d##, ERRORTYPE: %s
> 
> 8745 <class 'TypeError'> multiprocessing.pool.RemoteTraceback: """ Traceback (most recent call last): File "D:\anaconda3\envs\aaa\lib\multiprocessing\pool.py", line 119, in worker result = (True, func(*args, **kwds)) File "D:\代码复现\GaitSet_cpu_source\pretreatment.py", line 130, in cut_pickle img = cv2.imread(frame_path)[:, :, 0] TypeError: 'NoneType' object is not subscriptable """

**Comment by BoNiu-HZY** [comment]
您好，这个问题已经解决，是处理量受限，分批处理就好了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AbnerHqC/GaitSet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月8日(星期四) 上午9:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AbnerHqC/GaitSet] OU-MVLP数据预处理 (#146)





 
OU-MVLP数据预处理，源数据要按subject id-&gt;view 排，下载按view 0,30度下载的
  
@@***@***.***
 
JOB 32000 : --START-- Silhouette_015-01-06105
 
JOB 32000 : --FINISH-- Contain 52 valid frames. Saved to D:\DataSet\pretreatment\OU-MVLP\Silhouette_015-01\06105.
 
JOB 32500 : --START-- Silhouette_015-01-06629
 
JOB 32500 : --FINISH-- Contain 72 valid frames. Saved to D:\DataSet\pretreatment\OU-MVLP\Silhouette_015-01\06629.
 
JOB 33000 : --START-- Silhouette_015-01-07165
 
JOB 33000 : --FINISH-- Contain 52 valid frames. Saved to D:\DataSet\pretreatment\OU-MVLP\Silhouette_015-01\07165.
 
ERROR OCCUR: PID ##%d##, ERRORTYPE: %s
 
8745 <class 'TypeError'&gt; multiprocessing.pool.RemoteTraceback: """ Traceback (most recent call last): File "D:\anaconda3\envs\aaa\lib\multiprocessing\pool.py", line 119, in worker result = (True, func(*args, **kwds)) File "D:\代码复现\GaitSet_cpu_source\pretreatment.py", line 130, in cut_pickle img = cv2.imread(frame_path)[:, :, 0] TypeError: 'NoneType' object is not subscriptable """

**Comment by zhang123-sys** [comment]
您好，分批处理指OU-MVLP的batch size和CASIA-B一样？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月11日(星期二) 下午3:39
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [AbnerHqC/GaitSet] OU-MVLP数据预处理 (#146)





 您好，这个问题已经解决，是处理量受限，分批处理就好了。 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "AbnerHqC/GaitSet"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2022年9月8日(星期四) 上午9:33 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [AbnerHqC/GaitSet] OU-MVLP数据预处理 (#146) 
 
 
 
 
 
   
 OU-MVLP数据预处理，源数据要按subject id-&amp;gt;view 排，下载按view 0,30度下载的 
    
 @@***@***.*** 
   
 JOB 32000 : --START-- Silhouette_015-01-06105 
   
 JOB 32000 : --FINISH-- Contain 52 valid frames. Saved to D:\DataSet\pretreatment\OU-MVLP\Silhouette_015-01\06105. 
   
 JOB 32500 : --START-- Silhouette_015-01-06629 
   
 JOB 32500 : --FINISH-- Contain 72 valid frames. Saved to D:\DataSet\pretreatment\OU-MVLP\Silhouette_015-01\06629. 
   
 JOB 33000 : --START-- Silhouette_015-01-07165 
   
 JOB 33000 : --FINISH-- Contain 52 valid frames. Saved to D:\DataSet\pretreatment\OU-MVLP\Silhouette_015-01\07165. 
   
 ERROR OCCUR: PID ##%d##, ERRORTYPE: %s 
   
 8745 <class 'TypeError'&amp;gt; multiprocessing.pool.RemoteTraceback: """ Traceback (most recent call last): File "D:\anaconda3\envs\aaa\lib\multiprocessing\pool.py", line 119, in worker result = (True, func(*args, **kwds)) File "D:\代码复现\GaitSet_cpu_source\pretreatment.py", line 130, in cut_pickle img = cv2.imread(frame_path)[:, :, 0] TypeError: 'NoneType' object is not subscriptable """

**Comment by BoNiu-HZY** [comment]
你说的batch size是指的训练时的批数据大小吗？我这里的数据预处理指的是图片的预处理。我的分批处理方法是将OU-MVLP数据库整个Silhouette_000~Silhouette_270文件分成更小批文件处理（比如一次性只处理一个角度的文件图片）。因为报错是中途出现的，并不是在数据预处理（路径划分和图片尺度变换）的一开始就报错。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AbnerHqC/GaitSet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月11日(星期二) 下午3:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AbnerHqC/GaitSet] OU-MVLP数据预处理 (#146)





 您好，分批处理指OU-MVLP的batch size和CASIA-B一样？ 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: ***@***.***&amp;gt;;  
 发送时间: 2022年10月11日(星期二) 下午3:39 
 收件人: ***@***.***&amp;gt;;  
 抄送: ***@***.***&amp;gt;; ***@***.***&amp;gt;;  
 主题: Re: [AbnerHqC/GaitSet] OU-MVLP数据预处理 (#146) 
 
 
 
 
 
  您好，这个问题已经解决，是处理量受限，分批处理就好了。  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "AbnerHqC/GaitSet"                                                                                    ***@***.***&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2022年9月8日(星期四) 上午9:33  
  ***@***.***&amp;amp;gt;;  
  ***@***.******@***.***&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [AbnerHqC/GaitSet] OU-MVLP数据预处理 (#146)  
   
   
   
   
   
     
  OU-MVLP数据预处理，源数据要按subject id-&amp;amp;gt;view 排，下载按view 0,30度下载的  
      
  @@***@***.***  
     
  JOB 32000 : --START-- Silhouette_015-01-06105  
     
  JOB 32000 : --FINISH-- Contain 52 valid frames. Saved to D:\DataSet\pretreatment\OU-MVLP\Silhouette_015-01\06105.  
     
  JOB 32500 : --START-- Silhouette_015-01-06629  
     
  JOB 32500 : --FINISH-- Contain 72 valid frames. Saved to D:\DataSet\pretreatment\OU-MVLP\Silhouette_015-01\06629.  
     
  JOB 33000 : --START-- Silhouette_015-01-07165  
     
  JOB 33000 : --FINISH-- Contain 52 valid frames. Saved to D:\DataSet\pretreatment\OU-MVLP\Silhouette_015-01\07165.  
     
  ERROR OCCUR: PID ##%d##, ERRORTYPE: %s  
     
  8745 <class 'TypeError'&amp;amp;gt; multiprocessing.pool.RemoteTraceback: """ Traceback (most recent call last): File "D:\anaconda3\envs\aaa\lib\multiprocessing\pool.py", line 119, in worker result = (True, func(*args, **kwds)) File "D:\代码复现\GaitSet_cpu_source\pretreatment.py", line 130, in cut_pickle img = cv2.imread(frame_path)[:, :, 0] TypeError: 'NoneType' object is not subscriptable """
