### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by tangbinbinyes** [AbnerHqC/GaitSet#15]
/usr/bin/python3.5 /pycharmProject/GaitSet-master/train.py
Initialzing...
Initializing data source...
Data initialization complete.
Initializing model...
Model initialization complete.
Training START
Traceback (most recent call last):
  File "/pycharmProject/GaitSet-master/train.py", line 21, in <module>
    m.fit()
  File "/pycharmProject/GaitSet-master/model/model.py", line 150, in fit
    for seq, view, seq_type, label, batch_frame in train_loader:
  File "/home/tbb/.local/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 819, in __iter__
    return _DataLoaderIter(self)
  File "/home/tbb/.local/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 584, in __init__
    self._put_indices()
  File "/home/tbb/.local/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 646, in _put_indices
    indices = next(self.sample_iter, None)
  File "/pycharmProject/GaitSet-master/model/utils/sampler.py", line 19, in __iter__
    _index = random.choices(
AttributeError: module 'random' has no attribute 'choices'

**Comment by tangbinbinyes** [comment]
难道是我的python版本是3.5才报错的吗？

**Comment by AbnerHqC** [comment]
我没记错的话random应该是一个Python自带的包。你可以调试一下random.choice()

**Comment by tangbinbinyes** [comment]
我把choices改成choice之后又报错了，说choice接收了一个unexpected的值:k，如果我换成python3.6，是不是就会解决这个问题了呢？

**Comment by tangbinbinyes** [comment]
我换成Python3.6之后，就能运行了，谢谢你。

**Comment by tangbinbinyes** [comment]
Unfortunately, I have encountered new problems:
Traceback (most recent call last):
  File "/pycharmProject/GaitSet-master/train.py", line 21, in <module>
    m.fit()
  File "/pycharmProject/GaitSet-master/model/model.py", line 150, in fit
    for seq, view, seq_type, label, batch_frame in train_loader:
  File "/home/tbb/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 819, in __iter__
    return _DataLoaderIter(self)
  File "/home/tbb/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 584, in __init__
    self._put_indices()
  File "/home/tbb/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 646, in _put_indices
    indices = next(self.sample_iter, None)
  File "/pycharmProject/GaitSet-master/model/utils/sampler.py", line 15, in __iter__
    self.batch_size[0])
  File "/usr/lib/python3.6/random.py", line 320, in sample
    raise ValueError("Sample larger than population or is negative")
ValueError: Sample larger than population or is negative

**Comment by tangbinbinyes** [comment]
我知道怎么解决了，因为GPU显存小，训练的样本少，config里面设置的一次训练的个数超出了。谢谢。

**Comment by tangbinbinyes** [comment]
请问，这两个参数有什么用？
'pid_num': 73,
 'pid_shuffle': False,

**Comment by AbnerHqC** [comment]
您好，pid_num是选取前多少个人的样本用于训练。shuffle在casia上没有用，是说分割train和test的时候id是顺序的还是shuffle过的。

另外，上面你提到那个报错，应该和gpu没什么关系。是说你一个batch希望取出的人数大于了总的人数。config中batch_size第一维是每次取出的id数，第二维是每个id取的样本数。以pid_num=73为例，batch_size第一维应小于等于73。

很抱歉random.choices存在兼容性问题，感谢你提出这一问题。我会在后面的更新中更换这一函数，尽量使代码在Python3各个版本上都适用。
