### ISSUE TITLE
运行test脚本出错

### ISSUE THREAD

**Issue by Crane1043778796** [AbnerHqC/GaitSet#163]
```
Traceback (most recent call last):
  File "E:/gait-set/GaitSet-master/test.py", line 90, in <module>
    main()
  File "E:/gait-set/GaitSet-master/test.py", line 39, in main
    m = initialization(conf, test=opt.cache)[0]
  File "E:\gait-set\GaitSet-master\model\initialization.py", line 57, in initialization
    train_source, test_source = initialize_data(config, train, test)
  File "E:\gait-set\GaitSet-master\model\initialization.py", line 15, in initialize_data
    train_source, test_source = load_data(**config['data'], cache=(train or test))
  File "E:\gait-set\GaitSet-master\model\utils\data_loader.py", line 45, in load_data
    np.save(pid_fname, pid_list)
  File "<__array_function__ internals>", line 200, in save
  File "D:\Anaconda3\lib\site-packages\numpy\lib\npyio.py", line 521, in save
    arr = np.asanyarray(arr)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

```
其中dataloader.py约40行初
```
pid_list 
```
的内容是一个73长度的数组+一个长度50的数组把原数组分开了，请问你们也是这样吗 着急

**Comment by Chirag-Sharda** [comment]
found any fix for this? i am facing the same issue

**Comment by zjq1839** [comment]
numpy版本问题，我换到1.23.5解决了
