### ISSUE TITLE
训练集最少个数

### ISSUE THREAD

**Issue by tangbinbinyes** [AbnerHqC/GaitSet#17]
我今天想看看训练一个人要多少时间，把pid_num写成1，然后报错了

Traceback (most recent call last):
  File "/home/zhanghua/PycharmProjects/Convolutional-Neural-Network-Based-Gait-Recognition-master/GaitSet-master/train.py", line 21, in <module>
    m.fit()
  File "/home/zhanghua/PycharmProjects/Convolutional-Neural-Network-Based-Gait-Recognition-master/GaitSet-master/model/model.py", line 167, in fit
    ) = self.triplet_loss(triplet_feature, triplet_label)
  File "/home/zhanghua/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zhanghua/.local/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 143, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/zhanghua/.local/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 153, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/zhanghua/.local/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 83, in parallel_apply
    raise output
  File "/home/zhanghua/.local/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 59, in _worker
    output = module(*input, **kwargs)
  File "/home/zhanghua/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zhanghua/PycharmProjects/Convolutional-Neural-Network-Based-Gait-Recognition-master/GaitSet-master/model/network/triplet.py", line 23, in forward
    hard_hn_dist = torch.min(torch.masked_select(dist, hn_mask).view(n, m, -1), 2)[0]
RuntimeError: cannot perform reduction function min on tensor with no elements because the operation does not have an identity

Process finished with exit code 1

**Comment by AbnerHqC** [comment]
triplet loss至少要求3个人。
