### ISSUE TITLE
train.py 执行后无反应 RuntimeError: CuDNN error: CUDNN_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by miomiora** [AbnerHqC/GaitSet#170]
```bash
Initialzing...
Initializing data source...
Data initialization complete.
Initializing model...
Model initialization complete.
Training START
Traceback (most recent call last):
  File "train.py", line 21, in <module>
    m.fit()
  File "/home/czk/code/GaitSet/model/model.py", line 159, in fit
    feature, label_prob = self.encoder(*seq, batch_frame)
  File "/home/czk/anaconda3/envs/GaitSet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/czk/anaconda3/envs/GaitSet/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 121, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/czk/anaconda3/envs/GaitSet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/czk/code/GaitSet/model/network/gaitset.py", line 90, in forward
    x = self.set_layer1(x)
  File "/home/czk/anaconda3/envs/GaitSet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/czk/code/GaitSet/model/network/basic_blocks.py", line 24, in forward
    x = self.forward_block(x.view(-1,c,h,w))
  File "/home/czk/anaconda3/envs/GaitSet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/czk/code/GaitSet/model/network/basic_blocks.py", line 11, in forward
    x = self.conv(x)
  File "/home/czk/anaconda3/envs/GaitSet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/czk/anaconda3/envs/GaitSet/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: CuDNN error: CUDNN_STATUS_EXECUTION_FAILED
```
执行 `python train.py` 之后就无反应了，等很久之后会报这个错
```bash
pip list
Package         Version
--------------- ------------
certifi         2021.5.30
cffi            1.14.6
imageio         2.15.0
mkl-fft         1.0.6
mkl-random      1.0.1
numpy           1.15.4
opencv-python   4.1.2.30
pandas          1.1.5
Pillow          8.4.0
pip             21.2.2
pycparser       2.21
python-dateutil 2.8.2
pytz            2023.3.post1
scipy           1.5.4
setuptools      58.0.4
six             1.16.0
TBB             0.2
torch           0.4.1
wheel           0.37.1
xarray          0.16.2
```
执行 `python train.py` 过程中 GPU 只会有一点占用

**Comment by stormwyrmx** [comment]
请问楼主解决了吗，我也报的同样的错误：
Initialzing...
Initializing data source...
Loading training data...
Data initialization complete.
Initializing model...
Model initialization complete.
Training START
Traceback (most recent call last):
  File "train.py", line 20, in <module>
    m.fit()
  File "/home/wengyehao/code/GaitSet/model/model.py", line 159, in fit
    feature, label_prob = self.encoder(*seq, batch_frame)
  File "/home/wengyehao/anaconda3/envs/gaitset/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wengyehao/anaconda3/envs/gaitset/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 121, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/wengyehao/anaconda3/envs/gaitset/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wengyehao/code/GaitSet/model/network/gaitset.py", line 90, in forward
    x = self.set_layer1(x)
  File "/home/wengyehao/anaconda3/envs/gaitset/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wengyehao/code/GaitSet/model/network/basic_blocks.py", line 24, in forward
    x = self.forward_block(x.view(-1,c,h,w))
  File "/home/wengyehao/anaconda3/envs/gaitset/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wengyehao/code/GaitSet/model/network/basic_blocks.py", line 11, in forward
    x = self.conv(x)
  File "/home/wengyehao/anaconda3/envs/gaitset/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wengyehao/anaconda3/envs/gaitset/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: CuDNN error: CUDNN_STATUS_EXECUTION_FAILED

conda安装包：

#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
_openmp_mutex             5.1                       1_gnu
blas                      1.0                         mkl
bzip2                     1.0.8                h5eee18b_6
ca-certificates           2025.2.25            h06a4308_0
cairo                     1.16.0               hb05425b_5
certifi                   2021.5.30        py36h06a4308_0
cffi                      1.14.6           py36h400218f_0
cuda90                    1.0                  h6433d27_0    pytorch
cudatoolkit               9.0                  h13b8566_0
cudnn                     7.6.5                 cuda9.0_0
expat                     2.7.1                h6a678d5_0
ffmpeg                    4.0                  hcdf2ecd_0
fontconfig                2.14.1               h4c34cd2_2
freeglut                  3.4.0                h6a678d5_0
freetype                  2.13.3               h4a9f257_0
glib                      2.69.1               h4ff587b_1
graphite2                 1.3.14               h295c915_1
harfbuzz                  1.8.8                hffaf4a1_0
hdf5                      1.10.2               hba1933b_1
icu                       58.2                 he6710b0_3
imageio                   2.15.0                   pypi_0    pypi
intel-openmp              2025.0.0          h06a4308_1171
jasper                    2.0.14               hd8c5072_2
jpeg                      9e                   h5eee18b_3
ld_impl_linux-64          2.40                 h12ee557_0
lerc                      4.0.0                h6a678d5_0
libdeflate                1.22                 h5eee18b_0
libffi                    3.3                  he6710b0_2
libgcc-ng                 11.2.0               h1234567_1
libgfortran-ng            7.5.0               ha8ba4b0_17
libgfortran4              7.5.0               ha8ba4b0_17
libglu                    9.0.0                hf484d3e_1
libgomp                   11.2.0               h1234567_1
libopencv                 3.4.2                hb342d67_1
libopus                   1.3.1                h5eee18b_1
libpng                    1.6.39               h5eee18b_0
libstdcxx-ng              11.2.0               h1234567_1
libtiff                   4.5.1                hffd6297_1
libuuid                   1.41.5               h5eee18b_0
libvpx                    1.7.0                h439df22_0
libwebp-base              1.3.2                h5eee18b_1
libxcb                    1.15                 h7f8727e_0
libxml2                   2.10.4               hcbfbd50_0
lz4-c                     1.9.4                h6a678d5_1
mkl                       2018.0.3                      1
mkl_fft                   1.0.6            py36h7dd41cf_0
mkl_random                1.0.1            py36h4414c95_1
nccl                      1.3.5                 cuda9.0_0
ncurses                   6.4                  h6a678d5_0
ninja                     1.12.1               h06a4308_0
ninja-base                1.12.1               hdb19cb5_0
numpy                     1.15.4           py36h1d66e8a_0
numpy-base                1.15.4           py36h81de0dd_0
opencv                    3.4.2            py36h6fd60c2_1
openssl                   1.1.1w               h7f8727e_0
pandas                    1.1.5            py36h2531618_0
pcre                      8.45                 h295c915_0
pillow                    8.4.0                    pypi_0    pypi
pip                       21.2.2           py36h06a4308_0
pixman                    0.40.0               h7f8727e_1
py-opencv                 3.4.2            py36hb342d67_1
pycparser                 2.21               pyhd3eb1b0_0
python                    3.6.13               h12debd9_1
python-dateutil           2.8.2              pyhd3eb1b0_0
pytorch                   0.4.1            py36ha74772b_0
pytz                      2021.3             pyhd3eb1b0_0
readline                  8.2                  h5eee18b_0
setuptools                58.0.4           py36h06a4308_0
six                       1.16.0             pyhd3eb1b0_1
sqlite                    3.45.3               h5eee18b_0
tbb                       2022.0.0             hdb19cb5_0
tbb4py                    2021.3.0         py36hd09550d_0
tk                        8.6.14               h39e8969_0
wheel                     0.37.1             pyhd3eb1b0_0
xarray                    0.15.0                     py_0
xz                        5.6.4                h5eee18b_1
zlib                      1.2.13               h5eee18b_1
zstd                      1.5.6                hc292b87_0

**Comment by miomiora** [comment]
> 请问楼主解决了吗，我也报的同样的错误： Initialzing... Initializing data source... Loading training data... Data initialization complete. Initializing model... Model initialization complete. Training START Traceback (most recent call last): File "train.py", line 20, in m.fit() File "/home/wengyehao/code/GaitSet/model/model.py", line 159, in fit feature, label_prob = self.encoder(*seq, batch_frame) File "/home/wengyehao/anaconda3/envs/gaitset/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in **call** result = self.forward(*input, **kwargs) File "/home/wengyehao/anaconda3/envs/gaitset/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 121, in forward return self.module(*inputs[0], **kwargs[0]) File "/home/wengyehao/anaconda3/envs/gaitset/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in **call** result = self.forward(*input, **kwargs) File "/home/wengyehao/code/GaitSet/model/network/gaitset.py", line 90, in forward x = self.set_layer1(x) File "/home/wengyehao/anaconda3/envs/gaitset/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in **call** result = self.forward(*input, **kwargs) File "/home/wengyehao/code/GaitSet/model/network/basic_blocks.py", line 24, in forward x = self.forward_block(x.view(-1,c,h,w)) File "/home/wengyehao/anaconda3/envs/gaitset/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in **call** result = self.forward(*input, **kwargs) File "/home/wengyehao/code/GaitSet/model/network/basic_blocks.py", line 11, in forward x = self.conv(x) File "/home/wengyehao/anaconda3/envs/gaitset/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in **call** result = self.forward(*input, **kwargs) File "/home/wengyehao/anaconda3/envs/gaitset/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 301, in forward self.padding, self.dilation, self.groups) RuntimeError: CuDNN error: CUDNN_STATUS_EXECUTION_FAILED
> 
> conda安装包：
> 
> # Name Version Build Channel
> _libgcc_mutex 0.1 main _openmp_mutex 5.1 1_gnu blas 1.0 mkl bzip2 1.0.8 h5eee18b_6 ca-certificates 2025.2.25 h06a4308_0 cairo 1.16.0 hb05425b_5 certifi 2021.5.30 py36h06a4308_0 cffi 1.14.6 py36h400218f_0 cuda90 1.0 h6433d27_0 pytorch cudatoolkit 9.0 h13b8566_0 cudnn 7.6.5 cuda9.0_0 expat 2.7.1 h6a678d5_0 ffmpeg 4.0 hcdf2ecd_0 fontconfig 2.14.1 h4c34cd2_2 freeglut 3.4.0 h6a678d5_0 freetype 2.13.3 h4a9f257_0 glib 2.69.1 h4ff587b_1 graphite2 1.3.14 h295c915_1 harfbuzz 1.8.8 hffaf4a1_0 hdf5 1.10.2 hba1933b_1 icu 58.2 he6710b0_3 imageio 2.15.0 pypi_0 pypi intel-openmp 2025.0.0 h06a4308_1171 jasper 2.0.14 hd8c5072_2 jpeg 9e h5eee18b_3 ld_impl_linux-64 2.40 h12ee557_0 lerc 4.0.0 h6a678d5_0 libdeflate 1.22 h5eee18b_0 libffi 3.3 he6710b0_2 libgcc-ng 11.2.0 h1234567_1 libgfortran-ng 7.5.0 ha8ba4b0_17 libgfortran4 7.5.0 ha8ba4b0_17 libglu 9.0.0 hf484d3e_1 libgomp 11.2.0 h1234567_1 libopencv 3.4.2 hb342d67_1 libopus 1.3.1 h5eee18b_1 libpng 1.6.39 h5eee18b_0 libstdcxx-ng 11.2.0 h1234567_1 libtiff 4.5.1 hffd6297_1 libuuid 1.41.5 h5eee18b_0 libvpx 1.7.0 h439df22_0 libwebp-base 1.3.2 h5eee18b_1 libxcb 1.15 h7f8727e_0 libxml2 2.10.4 hcbfbd50_0 lz4-c 1.9.4 h6a678d5_1 mkl 2018.0.3 1 mkl_fft 1.0.6 py36h7dd41cf_0 mkl_random 1.0.1 py36h4414c95_1 nccl 1.3.5 cuda9.0_0 ncurses 6.4 h6a678d5_0 ninja 1.12.1 h06a4308_0 ninja-base 1.12.1 hdb19cb5_0 numpy 1.15.4 py36h1d66e8a_0 numpy-base 1.15.4 py36h81de0dd_0 opencv 3.4.2 py36h6fd60c2_1 openssl 1.1.1w h7f8727e_0 pandas 1.1.5 py36h2531618_0 pcre 8.45 h295c915_0 pillow 8.4.0 pypi_0 pypi pip 21.2.2 py36h06a4308_0 pixman 0.40.0 h7f8727e_1 py-opencv 3.4.2 py36hb342d67_1 pycparser 2.21 pyhd3eb1b0_0 python 3.6.13 h12debd9_1 python-dateutil 2.8.2 pyhd3eb1b0_0 pytorch 0.4.1 py36ha74772b_0 pytz 2021.3 pyhd3eb1b0_0 readline 8.2 h5eee18b_0 setuptools 58.0.4 py36h06a4308_0 six 1.16.0 pyhd3eb1b0_1 sqlite 3.45.3 h5eee18b_0 tbb 2022.0.0 hdb19cb5_0 tbb4py 2021.3.0 py36hd09550d_0 tk 8.6.14 h39e8969_0 wheel 0.37.1 pyhd3eb1b0_0 xarray 0.15.0 py_0 xz 5.6.4 h5eee18b_1 zlib 1.2.13 h5eee18b_1 zstd 1.5.6 hc292b87_0

这个我也忘记咋搞的了，后续用opengait跑了，opengait比较顺利，你可以试试
