### ISSUE TITLE
训练模型时报错： raise ValueError("Sample larger than population or is negative")

### ISSUE THREAD

**Issue by xiezq1989** [AbnerHqC/GaitSet#26]
(dl) root@a4b3f83c3f3c:/GaitSet-master# python train.py
/usr/local/miniconda3/envs/dl/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/usr/local/miniconda3/envs/dl/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Initialzing...
Initializing data source...
Loading training data...
Data initialization complete.
Initializing model...
Model initialization complete.
Training START
Traceback (most recent call last):
  File "train.py", line 21, in <module>
    m.fit()
  File "/GaitSet-master/model/model.py", line 150, in fit
    for seq, view, seq_type, label, batch_frame in train_loader:
  File "/usr/local/miniconda3/envs/dl/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 501, in __iter__
    return _DataLoaderIter(self)
  File "/usr/local/miniconda3/envs/dl/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 297, in __init__
    self._put_indices()
  File "/usr/local/miniconda3/envs/dl/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 345, in _put_indices
    indices = next(self.sample_iter, None)
  File "/GaitSet-master/model/utils/sampler.py", line 15, in __iter__
    self.batch_size[0])
  File "/usr/local/miniconda3/envs/dl/lib/python3.6/random.py", line 320, in sample
    raise ValueError("Sample larger than population or is negative")
ValueError: Sample larger than population or is negative

作者您好，请问这个报错怎么解决呢？

**Comment by zhuimengrenlin** [comment]
您好，我们也遇到了同样的问题 ValueError: Sample larger than population or is negative，能告诉我们您的解决方法吗？

**Comment by xiezq1989** [comment]
> 您好，我们也遇到了同样的问题 ValueError: Sample larger than population or is negative，能告诉我们您的解决方法吗？

您好，我当时报这个错是因为使用了有删减的训练集，后面换成完整的训练集后报错消失了。

**Comment by AbnerHqC** [comment]
如果训练集有删减的话，要对应调整训练人数。在config.py中的pid_num.

**Comment by changfufu** [comment]
我得是GTX970显卡，下的数据集是CASIA-B 剪影数据集。通过修改config中batch_size解决了该问题，修改为（2，16）。但是只能训练700轮，多了就内存溢出。。。

**Comment by changfufu** [comment]
好吧，还是有问题，用另一台配置稍好的电脑，同样的数据集和配置参数，但是还是有报这个错误，调整batch不能解决。调整pid_num后报错
`Initialzing...
Initializing data source...
Traceback (most recent call last):
  File "train.py", line 18, in <module>
    m = initialization(conf, train=opt.cache)[0]
  File "/home/wcf/GaitSet-master/model/initialization.py", line 57, in initialization
    train_source, test_source = initialize_data(config, train, test)
  File "/home/wcf/GaitSet-master/model/initialization.py", line 15, in initialize_data
    train_source, test_source = load_data(**config['data'], cache=(train or test))
  File "/home/wcf/GaitSet-master/model/utils/data_loader.py", line 42, in load_data
    pid_list = np.load(pid_fname)
  File "/home/wcf/anaconda3/envs/py36/lib/python3.6/site-packages/numpy/lib/npyio.py", line 453, in load
    pickle_kwargs=pickle_kwargs)
  File "/home/wcf/anaconda3/envs/py36/lib/python3.6/site-packages/numpy/lib/format.py", line 722, in read_array
    raise ValueError("Object arrays cannot be loaded when "
ValueError: Object arrays cannot be loaded when allow_pickle=False`

**Comment by aihanb** [comment]
> ValueError: Object arrays cannot be loaded when allow_pickle=False
你好，我之前也遇到了同样问题。现已经解决，方法是降低numpy版本:
pip install numpy=1.16.2

**Comment by aihanb** [comment]
> 好吧，还是有问题，用另一台配置稍好的电脑，同样的数据集和配置参数，但是还是有报这个错误，调整batch不能解决。调整pid_num后报错
> `Initialzing... Initializing data source... Traceback (most recent call last): File "train.py", line 18, in <module> m = initialization(conf, train=opt.cache)[0] File "/home/wcf/GaitSet-master/model/initialization.py", line 57, in initialization train_source, test_source = initialize_data(config, train, test) File "/home/wcf/GaitSet-master/model/initialization.py", line 15, in initialize_data train_source, test_source = load_data(**config['data'], cache=(train or test)) File "/home/wcf/GaitSet-master/model/utils/data_loader.py", line 42, in load_data pid_list = np.load(pid_fname) File "/home/wcf/anaconda3/envs/py36/lib/python3.6/site-packages/numpy/lib/npyio.py", line 453, in load pickle_kwargs=pickle_kwargs) File "/home/wcf/anaconda3/envs/py36/lib/python3.6/site-packages/numpy/lib/format.py", line 722, in read_array raise ValueError("Object arrays cannot be loaded when " ValueError: Object arrays cannot be loaded when allow_pickle=False`

你好，我之前也遇到了同样问题。现已经解决，方法是降低numpy版本:
pip install numpy=1.16.2

**Comment by 15229671718** [comment]
训练时一直报这个错：



Traceback (most recent call last):
  File "D:/Python_Demo/GaitSet-master/train.py", line 21, in <module>
    m.fit()
  File "D:\Python_Demo\GaitSet-master\model\model.py", line 159, in fit
    feature, label_prob = self.encoder(*seq, batch_frame)
  File "C:\Users\87615\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\87615\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\parallel\data_parallel.py", line 153, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "C:\Users\87615\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\Python_Demo\GaitSet-master\model\network\gaitset.py", line 89, in forward
    x = self.set_layer1(x)
  File "C:\Users\87615\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\Python_Demo\GaitSet-master\model\network\basic_blocks.py", line 23, in forward
    n, s, c, h, w = x.size()
ValueError: not enough values to unpack (expected 5, got 2)

**Comment by finding-dream** [comment]
Traceback (most recent call last):
  File "D:\Users\dell\PycharmProjects\GaitSet\train.py", line 30, in <module>
    m = initialization(conf, train=opt.cache)[0]# 返回initialization的第一个返回值m,m即model
  File "D:\Users\dell\PycharmProjects\GaitSet\model\initialization.py", line 63, in initialization
    train_source, test_source = initialize_data(config, train, test)
  File "D:\Users\dell\PycharmProjects\GaitSet\model\initialization.py", line 23, in initialize_data
    train_source.load_all_data()
  File "D:\Users\dell\PycharmProjects\GaitSet\model\utils\data_set.py", line 52, in load_all_data
    self.load_data(i)
  File "D:\Users\dell\PycharmProjects\GaitSet\model\utils\data_set.py", line 55, in load_data
    return self.__getitem__(index)
  File "D:\Users\dell\PycharmProjects\GaitSet\model\utils\data_set.py", line 86, in __getitem__
    data = [self.__loader__(_path) for _path in self.seq_dir[index]]
  File "D:\Users\dell\PycharmProjects\GaitSet\model\utils\data_set.py", line 86, in <listcomp>
    data = [self.__loader__(_path) for _path in self.seq_dir[index]]
  File "D:\Users\dell\PycharmProjects\GaitSet\model\utils\data_set.py", line 63, in __loader__
    return self.img2xarray(path)[:, :, self.cut_padding:-self.cut_padding].astype('float32') / 255.0
  File "D:\Users\dell\PycharmProjects\GaitSet\model\utils\data_set.py", line 118, in img2xarray
    data_dict = xr.DataArray(
  File "D:\Users\dell\anaconda3\envs\pytorch\lib\site-packages\xarray\core\dataarray.py", line 418, in __init__
    coords, dims = _infer_coords_and_dims(data.shape, coords, dims)
  File "D:\Users\dell\anaconda3\envs\pytorch\lib\site-packages\xarray\core\dataarray.py", line 132, in _infer_coords_and_dims
    raise ValueError(
ValueError: different number of dimensions on data and dims: 1 vs 3

Process finished with exit code 1
这个怎么解决呀？训练时候一直报这个错
