### ISSUE TITLE
运行错误ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

### ISSUE THREAD

**Issue by Allen-lz** [AbnerHqC/GaitSet#27]
作者你好，我在跑train.py时候在data_loader.py出现了ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'，但是服务器上已经有numpy模块，网上查找的方法都不适合，请问需要如何解决这个错误？

**Comment by AbnerHqC** [comment]
您好，我们在实验中没遇到过这个问题，请问您是否没有使用python3呢？

**Comment by AbnerHqC** [comment]
方便的话可以把具体错误完整的贴一下

**Comment by Allen-lz** [comment]
作者你好，以下是完整错误，我是用的python3.6.7。问题已经解决，错误原因是numpy版本过低，升级numpy的版本可以解决
Traceback (most recent call last):
  File "train.py", line 18, in <module>
    m = initialization(conf, train=opt.cache)[0]
  File "/home/home_data/lz/GaitSet/model/initialization.py", line 57, in initialization
    train_source, test_source = initialize_data(config, train, test)
  File "/home/home_data/lz/GaitSet/model/initialization.py", line 15, in initialize_data
    train_source, test_source = load_data(**config['data'], cache=(train or test))
  File "/home/home_data/lz/GaitSet/model/utils/data_loader.py", line 42, in load_data
    pid_list = np.load(pid_fname)
  File "/home/cv_user/anaconda3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 419, in load
    pickle_kwargs=pickle_kwargs)
  File "/home/cv_user/anaconda3/lib/python3.6/site-packages/numpy/lib/format.py", line 640, in read_array
    array = pickle.load(fp, **pickle_kwargs)
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

**Comment by AbnerHqC** [comment]
Nice~
