### ISSUE TITLE
pid_list = np.load(pid_fname)，TypeError: _reconstruct: First argument must be a sub-type of ndarray

### ISSUE THREAD

**Issue by Allen-lz** [AbnerHqC/GaitSet#29]
emmmm.....今天可能是动了什么包，导致了如下错误，望您解答一下！
Initialzing...
Initializing data source...
Traceback (most recent call last):
  File "train.py", line 18, in <module>
    m = initialization(conf, train=opt.cache)[0]
  File "/home/home_data/lz/GaitSet/model/initialization.py", line 57, in initialization
    train_source, test_source = initialize_data(config, train, test)
  File "/home/home_data/lz/GaitSet/model/initialization.py", line 15, in initialize_data
    train_source, test_source = load_data(**config['data'], cache=(train or test))
  File "/home/home_data/lz/GaitSet/model/utils/data_loader.py", line 42, in load_data
    pid_list = np.load(pid_fname)
  File "/home/cv_user/anaconda3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 433, in load
    pickle_kwargs=pickle_kwargs)
  File "/home/cv_user/anaconda3/lib/python3.6/site-packages/numpy/lib/format.py", line 657, in read_array
    array = pickle.load(fp, **pickle_kwargs)
TypeError: _reconstruct: First argument must be a sub-type of ndarray

**Comment by Allen-lz** [comment]
你好作者，上述问题我已经解决了，重写了一个CASIA-B_73_False.npy文件。
接下来出现了以下错误：
Initialzing...
Initializing data source...
Loading training data...
Data initialization complete.
Initializing model...
Model initialization complete.
Training START
Traceback (most recent call last):
  File "train.py", line 21, in <module>
    m.fit()
  File "/home/home_data/lz/GaitSet/model/model.py", line 179, in fit
    loss.backward()
  File "/home/cv_user/anaconda3/lib/python3.6/site-packages/torch/tensor.py", line 93, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/cv_user/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: CUDA error: out of memory
但是我之前反复跑成功许多次，都没有出现显存不够的错误，请问是不是pytorch版本的原因导致其tensor占用的显存变大了，之前我是Pytorch1.0，现在降为了0,4.1版本

**Comment by Allen-lz** [comment]
多次打扰很抱歉。RuntimeError: CUDA eor: out of memory确实是Pytorch版本的原因导致

**Comment by AbnerHqC** [comment]
您好，抱歉现在才回复。第一个问题应该是缓存本地的pid_list损坏了，建议将本地的npy都删除，代码会重建pid_list。第二个问题不知是否和您重写的npy有关，我们有在PyTorch1.0和0.4.1上都进行过测试，应该不会有太大的显存使用差异。按照batch_size=(8,16)的配置使用2块11G显卡应该可以放下。

**Comment by Allen-lz** [comment]
感谢作者在百忙之中抽时间回答问题，我的是11g的卡，用Pytorch1.0刚刚好按照batch_size=(8,16)满显存运行，问题已经解决。
