### ISSUE TITLE
training START

### ISSUE THREAD

**Issue by Cyprusky** [AbnerHqC/GaitSet#32]
在执行train.py后 报以下错误 memory error请问这如何解决？感谢您。我的配置是GTX950 cuda9 csdnn7 py3.6 pytorch0.4

Initialzing...
Initializing data source...
Loading training data...
Data initialization complete.
Initializing model...
Model initialization complete.
Training START
Traceback (most recent call last):
  File "train.py", line 21, in <module>
    m.fit()
  File "D:\DL\GaitSet-master\model\model.py", line 150, in fit
    for seq, view, seq_type, label, batch_frame in train_loader:
  File "C:\Users\Cyprus\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\utils\data\dataloader.py", line 501, in __iter__
    return _DataLoaderIter(self)
  File "C:\Users\Cyprus\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\utils\data\dataloader.py", line 289, in __init__
    w.start()
  File "C:\Users\Cyprus\AppData\Local\Programs\Python\Python36\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\Cyprus\AppData\Local\Programs\Python\Python36\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\Cyprus\AppData\Local\Programs\Python\Python36\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\Cyprus\AppData\Local\Programs\Python\Python36\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\Cyprus\AppData\Local\Programs\Python\Python36\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
MemoryError
Initialzing...
Initializing data source...
Loading training data...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Cyprus\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\Cyprus\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Users\Cyprus\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\Cyprus\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\Cyprus\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\Cyprus\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\Cyprus\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\DL\GaitSet-master\train.py", line 18, in <module>
    m = initialization(conf, train=opt.cache)[0]
  File "D:\DL\GaitSet-master\model\initialization.py", line 57, in initialization
    train_source, test_source = initialize_data(config, train, test)
  File "D:\DL\GaitSet-master\model\initialization.py", line 18, in initialize_data
    train_source.load_all_data()
  File "D:\DL\GaitSet-master\model\utils\data_set.py", line 45, in load_all_data
    self.load_data(i)
  File "D:\DL\GaitSet-master\model\utils\data_set.py", line 48, in load_data
    return self.__getitem__(index)
  File "D:\DL\GaitSet-master\model\utils\data_set.py", line 62, in __getitem__
    data = [self.__loader__(_path) for _path in self.seq_dir[index]]
  File "D:\DL\GaitSet-master\model\utils\data_set.py", line 62, in <listcomp>
    data = [self.__loader__(_path) for _path in self.seq_dir[index]]
  File "D:\DL\GaitSet-master\model\utils\data_set.py", line 53, in __loader__
    'float32') / 255.0
  File "C:\Users\Cyprus\AppData\Local\Programs\Python\Python36\lib\site-packages\xarray\core\dataarray.py", line 1954, in func
    **kwargs))
  File "C:\Users\Cyprus\AppData\Local\Programs\Python\Python36\lib\site-packages\xarray\core\ops.py", line 207, in func
    return _call_possibly_missing_method(self, name, args, kwargs)
  File "C:\Users\Cyprus\AppData\Local\Programs\Python\Python36\lib\site-packages\xarray\core\ops.py", line 194, in _call_possibly_missing_method
    return method(*args, **kwargs)
MemoryError

**Comment by AbnerHqC** [comment]
您好，看起来像是内存不足了。您可以尝试一下`python train.py --cache=false`。这样不会将数据一次性读进内存。但是这样可能会使训练变慢。

**Comment by Cyprusky** [comment]
> 您好，看起来像是内存不足了。您可以尝试一下`python train.py --cache=false`。这样不会将数据一次性读进内存。但是这样可能会使训练变慢。

十分感谢您的帮助，谢谢。
