### ISSUE TITLE
您好，请教您几个问题

### ISSUE THREAD

**Issue by snail0614** [AbnerHqC/GaitSet#33]
1、在运行train.py时，报下面错误：
Initialzing...
Initializing data source...
Loading training data...
Data initialization complete.
Initializing model...
Model initialization complete.
Training START
Traceback (most recent call last):
  File "train.py", line 21, in <module>
    m.fit()
  File "/home/xkk/Desktop/GaiSet/GaitSet-master/model/model.py", line 150, in fit
    for seq, view, seq_type, label, batch_frame in train_loader:
  File "/home/software_mount/xkk/local_install/python3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 451, in __iter__
    return _DataLoaderIter(self)
  File "/home/software_mount/xkk/local_install/python3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 247, in __init__
    self._put_indices()
  File "/home/software_mount/xkk/local_install/python3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 295, in _put_indices
    indices = next(self.sample_iter, None)
  File "/home/xkk/Desktop/GaiSet/GaitSet-master/model/utils/sampler.py", line 15, in __iter__
    self.batch_size[0])
  File "/home/software_mount/xkk/local_install/python3/lib/python3.6/random.py", line 318, in sample
    raise ValueError("Sample larger than population or is negative")
ValueError: Sample larger than population or is negative
2、在运行test.py时，报下面错误：
Initialzing...
Initializing data source...
Data initialization complete.
Initializing model...
Model initialization complete.
Loading the model of iteration 80000...
Transforming...
Traceback (most recent call last):
  File "test.py", line 42, in <module>
    test = m.transform('test', opt.batch_size)
  File "/home/xkk/Desktop/GaiSet/GaitSet-master/model/model.py", line 259, in transform
    return np.concatenate(feature_list, 0), view_list, seq_type_list, label_list
ValueError: need at least one array to concatenate

请问：
您知道是什么原因吗？可能问题有点简单，但调试了两天不知道哪里有问题，期待您的解答～

还有一个问题是，config.py中的'dataset_path'是填写预处理之后的图片路径吗？如果不是的话，那预处理之后的图片在什么时候使用，谢谢您

**Comment by snail0614** [comment]
您好，之前没注意到Closed issues，今天在Closed issues中看到了一些问题，train.py现在可以运行了。我是在config.py中的'dataset_path'填写的是预处理之后的图片路径，尝试将pid_num更改为30后就可以正常运行了，不知道是什么原因？但是在训练结束后，运行test.py报下面错误：
Initialzing...
Initializing data source...
Data initialization complete.
Initializing model...
Model initialization complete.
Loading the model of iteration 80000...
Transforming...
---------------data_loader  in model.py
---------------i,x=  in model.py 0 [[array([[[[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        ...,

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]]]], dtype=float32)], ['000'], ['bg-01'], ['017'], array([[104]])]
Traceback (most recent call last):
  File "test.py", line 42, in <module>
    test = m.transform('test', opt.batch_size)
  File "/home/xkk/Desktop/GaiSet/GaitSet-master/model/model.py", line 246, in transform
    print(batch_frame, np.sum(batch_frame))
  File "/home/software_mount/xkk/local_install/python3/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 2076, in sum
    initial=initial)
  File "/home/software_mount/xkk/local_install/python3/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 84, in _wrapreduction
    return reduction(axis=axis, out=out, **passkwargs)
TypeError: sum() received an invalid combination of arguments - got (out=NoneType, axis=NoneType, ), but expected one of:
 * ()
 * (torch.dtype dtype)
 * (int dim, torch.dtype dtype)
      didn't match because some of the keywords were incorrect: out, axis
 * (int dim, bool keepdim, torch.dtype dtype)
 * (int dim, bool keepdim)
      didn't match because some of the keywords were incorrect: out, axis

**Comment by Cyprusky** [comment]
您好，您是用的windows系统进行测试的吗？我的train.py执行出现问题了，能和我说说你的实施细节吗？十分感谢！

**Comment by Cyprusky** [comment]
> 您好，之前没注意到Closed issues，今天在Closed issues中看到了一些问题，train.py现在可以运行了。我是在config.py中的'dataset_path'填写的是预处理之后的图片路径，尝试将pid_num更改为30后就可以正常运行了，不知道是什么原因？但是在训练结束后，运行test.py报下面错误：
> Initialzing...
> Initializing data source...
> Data initialization complete.
> Initializing model...
> Model initialization complete.
> Loading the model of iteration 80000...
> Transforming...
> ---------------data_loader in model.py
> ---------------i,x= in model.py 0 [[array([[[[0., 0., 0., ..., 0., 0., 0.],
> [0., 0., 0., ..., 0., 0., 0.],
> [0., 0., 0., ..., 0., 0., 0.],
> ...,
> [0., 0., 0., ..., 0., 0., 0.],
> [0., 0., 0., ..., 0., 0., 0.],
> [0., 0., 0., ..., 0., 0., 0.]],
> 
> ```
>     [[0., 0., 0., ..., 0., 0., 0.],
>      [0., 0., 0., ..., 0., 0., 0.],
>      [0., 0., 0., ..., 0., 0., 0.],
>      ...,
>      [0., 0., 0., ..., 0., 0., 0.],
>      [0., 0., 0., ..., 0., 0., 0.],
>      [0., 0., 0., ..., 0., 0., 0.]],
> 
>     [[0., 0., 0., ..., 0., 0., 0.],
>      [0., 0., 0., ..., 0., 0., 0.],
>      [0., 0., 0., ..., 0., 0., 0.],
>      ...,
>      [0., 0., 0., ..., 0., 0., 0.],
>      [0., 0., 0., ..., 0., 0., 0.],
>      [0., 0., 0., ..., 0., 0., 0.]],
> 
>     ...,
> 
>     [[0., 0., 0., ..., 0., 0., 0.],
>      [0., 0., 0., ..., 0., 0., 0.],
>      [0., 0., 0., ..., 0., 0., 0.],
>      ...,
>      [0., 0., 0., ..., 0., 0., 0.],
>      [0., 0., 0., ..., 0., 0., 0.],
>      [0., 0., 0., ..., 0., 0., 0.]],
> 
>     [[0., 0., 0., ..., 0., 0., 0.],
>      [0., 0., 0., ..., 0., 0., 0.],
>      [0., 0., 0., ..., 0., 0., 0.],
>      ...,
>      [0., 0., 0., ..., 0., 0., 0.],
>      [0., 0., 0., ..., 0., 0., 0.],
>      [0., 0., 0., ..., 0., 0., 0.]],
> 
>     [[0., 0., 0., ..., 0., 0., 0.],
>      [0., 0., 0., ..., 0., 0., 0.],
>      [0., 0., 0., ..., 0., 0., 0.],
>      ...,
>      [0., 0., 0., ..., 0., 0., 0.],
>      [0., 0., 0., ..., 0., 0., 0.],
>      [0., 0., 0., ..., 0., 0., 0.]]]], dtype=float32)], ['000'], ['bg-01'], ['017'], array([[104]])]
> ```
> Traceback (most recent call last):
> File "test.py", line 42, in 
> test = m.transform('test', opt.batch_size)
> File "/home/xkk/Desktop/GaiSet/GaitSet-master/model/model.py", line 246, in transform
> print(batch_frame, np.sum(batch_frame))
> File "/home/software_mount/xkk/local_install/python3/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 2076, in sum
> initial=initial)
> File "/home/software_mount/xkk/local_install/python3/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 84, in _wrapreduction
> return reduction(axis=axis, out=out, **passkwargs)
> TypeError: sum() received an invalid combination of arguments - got (out=NoneType, axis=NoneType, ), but expected one of:
> 
> * ()
> * (torch.dtype dtype)
> * (int dim, torch.dtype dtype)
>   didn't match because some of the keywords were incorrect: out, axis
> * (int dim, bool keepdim, torch.dtype dtype)
> * (int dim, bool keepdim)
>   didn't match because some of the keywords were incorrect: out, axis

您好，您是用的windows系统进行测试的吗？我的train.py执行出现问题了，能和我说说你的实施细节吗？十分感谢！

**Comment by snail0614** [comment]
抱歉，我用的是ubuntu16，你可以把你的问题提出来@Cyprusky

**Comment by snail0614** [comment]
之前没注意到Closed issues，今天在Closed issues中看到了一些问题，现在可以运行了。我是在config.py中的'dataset_path'填写的是预处理之后的图片路径，尝试将pid_num更改为30后就可以正常运行了，不知道是什么原因？

**Comment by Cyprusky** [comment]
> 之前没注意到Closed issues，今天在Closed issues中看到了一些问题，现在可以运行了。我是在config.py中的'dataset_path'填写的是预处理之后的图片路径，尝试将pid_num更改为30后就可以正常运行了，不知道是什么原因？

那我再尝试一下  谢谢帮助

**Comment by aldotripolyta** [comment]
@Cyprusky whait your directory syntax for 
dataset_path
WORK_PATH
CUDA_VISIBLE_DEVICES

are there same with --input_path & --output_path?
Hope you can answer.

**Comment by 845603761** [comment]
> > 之前没注意到Closed issues，今天在Closed issues中看到了一些问题，现在可以运行了。我是在config.py中的'dataset_path'填写的是预处理之后的图片路径，尝试将pid_num更改为30后就可以正常运行了，不知道是什么原因？
> 
> 那我再尝试一下 谢谢帮助

您好，snail0614 ！感谢你在百忙之中抽空！我在运行test.py文件时候 遇到了一个bug：
Initialzing...
Initializing data source...
Data initialization complete.
Initializing model...
Model initialization complete.
Loading the model of iteration 80000...
Transforming...
Evaluating...
Traceback (most recent call last):
  File "test.py", line 44, in <module>
    acc = evaluation(test, conf['data'])
  File "/home/chenwei/下载/GaitSet-master/model/utils/evaluator.py", line 47, in evaluation
    0) * 100 / dist.shape[0], 2)
ValueError: could not broadcast input array from shape (0) into shape (5)
我在网络上得知L报这种类型的错误，因为你输入数据的尺寸和网络需要的尺寸不一致，才会报错
而且我发现你也有输出类似列表的形式，所以很想请教下您，请问在运行test.py之前需要改什么吗？
（我在运行train.py训练模型的时候，config.py中 已经把dataset_path改成了 与处理之后的数据集B 的路径 这是否错误？ 其次 我的pid_num也改成了30，然后，我的config.py中的batch_size改成了（2，4））
诚挚的希望你能够帮助我 谢谢！

**Comment by aldotripolyta** [comment]
> > > 之前没注意到Closed issues，今天在Closed issues中看到了一些问题，现在可以运行了。我是在config.py中的'dataset_path'填写的是预处理之后的图片路径，尝试将pid_num更改为30后就可以正常运行了，不知道是什么原因？
> > 
> > 
> > 那我再尝试一下 谢谢帮助
> 
> 您好，snail0614 ！感谢你在百忙之中抽空！我在运行test.py文件时候 遇到了一个bug：
> Initialzing...
> Initializing data source...
> Data initialization complete.
> Initializing model...
> Model initialization complete.
> Loading the model of iteration 80000...
> Transforming...
> Evaluating...
> Traceback (most recent call last):
> File "test.py", line 44, in 
> acc = evaluation(test, conf['data'])
> File "/home/chenwei/下载/GaitSet-master/model/utils/evaluator.py", line 47, in evaluation
> 0) * 100 / dist.shape[0], 2)
> ValueError: could not broadcast input array from shape (0) into shape (5)
> 我在网络上得知： 报这种类型的错误，因为你输入数据的尺寸和网络需要的尺寸不一致，才会报错
> 而且我发现你也有输出类似列表的形式，所以很想请教下您，请问在运行test.py之前需要改什么吗 我除了config.py文件改了一些参数 其他都没改？
> （PS：我早在运行train.py训练模型的时候，config.py中 已经把dataset_path改成了 预处理之后的数据集B 的路径 ，而不是向您后面解决问题所说在test时才改了路径，这是否是错误的？ 其次 我的pid_num也改成了30，然后，我的config.py中的batch_size改成了（2，4）因为会超出内存）
> 诚挚的希望你能够帮助我 谢谢！

@845603761 hey, I just got a problem that's same with you. Can you share if you can solve your problem? Thank you.
