### ISSUE TITLE
在Test.py时遇到了value Error 求作者大大帮忙..

### ISSUE THREAD

**Issue by 845603761** [AbnerHqC/GaitSet#36]
您好， AbnerHqc！这是我第二次发帖了（上次还在问能不能问windows10做 然后这段时间换成了ubuntu）感谢你在百忙之中抽空！我在运行test.py文件时候 遇到了一个bug：
Initialzing...
Initializing data source...
Data initialization complete.
Initializing model...
Model initialization complete.
Loading the model of iteration 80000...
Transforming...
Evaluating...
Traceback (most recent call last):
File "test.py", line 44, in 
acc = evaluation(test, conf['data'])
File "/home/chenwei/下载/GaitSet-master/model/utils/evaluator.py", line 47, in evaluation
0) * 100 / dist.shape[0], 2)

！！！！！ValueError: could not broadcast input array from shape (0) into shape (5)

我在网络上得知： 报这种类型的错误，因为你输入数据的尺寸和网络需要的尺寸不一致，才会报错
所以很想请教下您，请问在运行test.py之前需要改什么吗 我除了config.py文件改了一些参数，其他都没有改。
（PS：我早在运行train.py训练模型的时候，config.py中 已经把dataset_path改成了 预处理之后的数据集B 的路径 ；其次我的pid_num也改成了30；然后，我的config.py中的batch_size改成了（2，4）因为之前我上面都没改动的时候也会发生Memory Error 提示我内存不够 当时我没改cache的值 ）
难道是因为batch_size的原因吗？
诚挚的希望你能够帮助我 谢谢！

**Comment by 845603761** [comment]
如果只能把cache的值变成false的话那我就试一试，主要我的GTX960M 迭代了80000 花了6.7个小时好久。。

**Comment by AbnerHqC** [comment]
你好，因为我调试的时候没有出现你贴出的这个错误，所以光看这个也不大猜得出为啥shape会是0。可能您得把evaluation里面最后一句话嵌套的几个函数拆开后输出来看看是什么地方不正常。不知道有没有其他童鞋也遇到了这样的问题。

关于Memory Error，由于问题https://github.com/AbnerHqC/GaitSet/issues/32 中贴出的错误是报在load的时候所以猜测是`--cache`参数的问题。不知您的memory error是报在什么地方？更改batch_size应该只能解决显存不足的问题对应报错应该是CUDA xxxxx。没法解决内存溢出的问题。

**Comment by Cyprusky** [comment]
> 你好，因为我调试的时候没有出现你贴出的这个错误，所以光看这个也不大猜得出为啥shape会是0。可能您得把evaluation里面最后一句话嵌套的几个函数拆开后输出来看看是什么地方不正常。不知道有没有其他童鞋也遇到了这样的问题。
> 
> 关于Memory Error，由于问题#32 中贴出的错误是报在load的时候所以猜测是`--cache`参数的问题。不知您的memory error是报在什么地方？更改batch_size应该只能解决显存不足的问题对应报错应该是CUDA xxxxx。没法解决内存溢出的问题。
> 
> 关于训练时间，我们跑实验的时候batch_size是128，8w个iter用4个1080ti大概也得一夜的 ;)

作者大大你好，我的电脑配置是GTX950m，可能配置有点低，在运行test.py的时候只迭代了21200，请问这对结果有什么影响吗？十分感谢作者大大抽空回答问题，十分感谢

**Comment by 845603761** [comment]
> 你好，因为我调试的时候没有出现你贴出的这个错误，所以光看这个也不大猜得出为啥shape会是0。可能您得把evaluation里面最后一句话嵌套的几个函数拆开后输出来看看是什么地方不正常。不知道有没有其他童鞋也遇到了这样的问题。
> 
> 关于Memory Error，由于问题#32 中贴出的错误是报在load的时候所以猜测是`--cache`参数的问题。不知您的memory error是报在什么地方？更改batch_size应该只能解决显存不足的问题对应报错应该是CUDA xxxxx。没法解决内存溢出的问题。
> 
> 关于训练时间，我们跑实验的时候batch_size是128，8w个iter用4个1080ti大概也得一夜的 ;)

谢谢您的回复！ 我刚刚把config.py中的batch_size改回了您原来发布的（4，16）（但是 pid_num还是30 ，如果我改了这个参数后就是另一个OS ERROR了 如果您有时间 可以看看底下一个帖子..）  
然后出现了以下error
Initialzing...
Initializing data source...
Loading training data...
Data initialization complete.
Initializing model...
Model initialization complete.
Training START
Traceback (most recent call last):
  File "train.py", line 21, in <module>
    m.fit()
  File "/home/chenwei/下载/GaitSet-master/model/model.py", line 159, in fit
    feature, label_prob = self.encoder(*seq, batch_frame)
  File "/home/chenwei/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/chenwei/.local/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 141, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/chenwei/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/chenwei/下载/GaitSet-master/model/network/gaitset.py", line 90, in forward
    x = self.set_layer1(x)
  File "/home/chenwei/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/chenwei/下载/GaitSet-master/model/network/basic_blocks.py", line 24, in forward
    x = self.forward_block(x.view(-1,c,h,w))
  File "/home/chenwei/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/chenwei/下载/GaitSet-master/model/network/basic_blocks.py", line 11, in forward
    x = self.conv(x)
  File "/home/chenwei/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/chenwei/.local/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 320, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDA out of memory. Tried to allocate 1.29 GiB (GPU 0; 1.96 GiB total capacity; 51.15 MiB already allocated; 1.23 GiB free; 872.50 KiB cached)

确实和您预测的一样：）这是一个CUDA 的问题  我当时是上网查了一下有人是改了batch_size的大小 ，然后我看到代码中也有这个参数  然后我就调整了下（其实我不太懂这个应该怎么调当时就随便改了以下...sorry 我之前调成了（4，8）这种也是有问题的）

**Comment by 845603761** [comment]
> 你好，因为我调试的时候没有出现你贴出的这个错误，所以光看这个也不大猜得出为啥shape会是0。可能您得把evaluation里面最后一句话嵌套的几个函数拆开后输出来看看是什么地方不正常。不知道有没有其他童鞋也遇到了这样的问题。
> 
> 关于Memory Error，由于问题#32 中贴出的错误是报在load的时候所以猜测是`--cache`参数的问题。不知您的memory error是报在什么地方？更改batch_size应该只能解决显存不足的问题对应报错应该是CUDA xxxxx。没法解决内存溢出的问题。
> 
> 关于训练时间，我们跑实验的时候batch_size是128，8w个iter用4个1080ti大概也得一夜的 ;)

您好，这是我把config.py的pid_num也改成了 您所设置的70 除了dataset_path都没变了 
然后发生了以下error
Initialzing...
Initializing data source...
Loading training data...
Data initialization complete.
Initializing model...
Model initialization complete.
Training START
Traceback (most recent call last):
  File "train.py", line 21, in <module>
    m.fit()
  File "/home/chenwei/下载/GaitSet-master/model/model.py", line 150, in fit
    for seq, view, seq_type, label, batch_frame in train_loader:
  File "/home/chenwei/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 819, in __iter__
    return _DataLoaderIter(self)
  File "/home/chenwei/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 560, in __init__
    w.start()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.6/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/lib/python3.6/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_fork.py", line 66, in _launch
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory

感觉改成了70以后 就好卡了。。 
想问以下作者 有什么综合可以解决的方法吗？ （最后作者您说的跑了一天是test.py吗 我看您说的是训练（train.py?) 不过batch-size改成128好像只有在test.py吧 难道我这6小时又错了：（ ）

**Comment by jcrazy1997** [comment]
@845603761 OSError: [Errno 12] Cannot allocate memory这个问题如果是在训练的时候出现的话，应该是内存不足导致的，可以尝试下在train.py 后面加上参数--cache=false，如果是显存不足的话，应该可以考虑降低config中的batch_size，不知道理解有没有错，希望作者可以看下。

**Comment by 845603761** [comment]
> @845603761 OSError: [Errno 12] Cannot allocate memory这个问题如果是在训练的时候出现的话，应该是内存不足导致的，可以尝试下在train.py 后面加上参数--cache=false，如果是显存不足的话，应该可以考虑降低config中的batch_size，不知道理解有没有错，希望作者可以看下。

首先十分感谢您的回复：） ！ 作者确实之前有这样说过，不过我想问下您，比如我之前改了bath_size的大小（在运行train.py时 没输入--cache=false 因为当时没有报这个 memory error了）， 当我训练完成后，运行test.py 就会出现VALUE ERROR （具体如果您有空的话 就是1.2楼我发的那个错误情况 类型不匹配），请问您这种情况需要怎么改参数呢 ？

**Comment by 845603761** [comment]
请问作者还有空帮我看下这个问题吗...

**Comment by Cyprusky** [comment]
昨天还能成功运行test.py  今天我只是划分了一下训练和数据及，不知到为什么就报这个错，请问如何解决呢？


Initialzing...
Initializing data source...
Data initialization complete.
Initializing model...
Model initialization complete.
Loading the model of iteration 10000...
Transforming...
Traceback (most recent call last):
  File "test.py", line 42, in <module>
    test = m.transform('test', opt.batch_size)
  File "/media/cyprus/Data/DL/GaitSet-master/model/model.py", line 252, in transform
    return np.concatenate(feature_list, 0), view_list, seq_type_list, label_list
ValueError: need at least one array to concatenate

**Comment by aldotripolyta** [comment]
@Cyprusky hey cybrusky, I got a problem that's same with you. So, can you solve your problem now? Hope you can answer. Thank you.

**Comment by OnlyFlashEobard** [comment]
您好，我也遇到同样的ValueError的问题，想请教一下解决方法。。。。

**Comment by wxbs** [comment]
> 您好！请问这个问题您解决了吗？我也遇到了相同的问题，谢谢您！

**Comment by wxbs** [comment]
> 昨天还能成功运行test.py 今天我只是划分了一下训练和数据及，不知到为什么就报这个错，请问如何解决呢？
> 
> Initialzing... Initializing data source... Data initialization complete. Initializing model... Model initialization complete. Loading the model of iteration 10000... Transforming... Traceback (most recent call last): File "test.py", line 42, in test = m.transform('test', opt.batch_size) File "/media/cyprus/Data/DL/GaitSet-master/model/model.py", line 252, in transform return np.concatenate(feature_list, 0), view_list, seq_type_list, label_list ValueError: need at least one array to concatenate

您好！请问这个问题您解决了吗？我也遇到了相同的问题，谢谢您！
