### ISSUE TITLE
train 训练出错

### ISSUE THREAD

**Issue by zhuimengrenlin** [AbnerHqC/GaitSet#54]
Initialzing...
Initializing data source...
Loading training data...
Data initialization complete.
Initializing model...
Model initialization complete.
Training START
Traceback (most recent call last):
  File "/home/dayday/桌面/GaitSet-master/train.py", line 21, in <module>
    m.fit()
  File "/home/dayday/桌面/GaitSet-master/model/model.py", line 150, in fit
    for seq, view, seq_type, label, batch_frame in train_loader:
  File "/home/dayday/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 819, in __iter__
    return _DataLoaderIter(self)
  File "/home/dayday/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 584, in __init__
    self._put_indices()
  File "/home/dayday/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 646, in _put_indices
    indices = next(self.sample_iter, None)
  File "/home/dayday/桌面/GaitSet-master/model/utils/sampler.py", line 15, in __iter__
    self.batch_size[0])
  File "/home/dayday/anaconda3/lib/python3.6/random.py", line 317, in sample
    raise ValueError("Sample larger than population or is negative")
ValueError: Sample larger than population or is negative

Process finished with exit code 1
问一下，这个问题怎么解决。谢谢

**Comment by AbnerHqC** [comment]
您是否调整了数据集？是的话可以参考 [issue#26](https://github.com/AbnerHqC/GaitSet/issues/26)
