### ISSUE TITLE
模型输入图像大小

### ISSUE THREAD

**Issue by cyummy** [AbnerHqC/GaitSet#56]
您好，请教个有关模型输入图像大小的问题。
如果把模型输入图像的大小由64*64*1改成128*128*1，并且调整gaitset.py中模型结构，使经过卷积和池化，最终得到特征大小为16*16*128。除了需要改动config.py中resolution参数，还有其他地方需要修改吗？

另外，想问下你们在实验的过程中，有尝试过更大尺寸的输入吗？如果增大模型的输入尺寸，在卷积层参数的设计选择上，可以分享下调参经验吗？（捂脸

谢谢！

**Comment by cyummy** [comment]
当我把模型输入图像大小改成128，尝试训练模型的时候，发生了以下这样的错误，是物理内存的原因不够了吗？
电脑配置：ubuntu16.04 + python3.6  + pytorch1.0 + 双显卡1080ti 

Initialzing...
Initializing data source...
Loading training data...
Data initialization complete.
Initializing model...
Model initialization complete.
Training START
Traceback (most recent call last):
  File "train.py", line 23, in <module>
    m.fit()
  File "/home/cyummy/GaitSet/model_128/model/model.py", line 151, in fit
    for seq, view, seq_type, label, batch_frame in train_loader:
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 819, in __iter__
    return _DataLoaderIter(self)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 560, in __init__
    w.start()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.6/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/lib/python3.6/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_fork.py", line 66, in _launch
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory

**Comment by AbnerHqC** [comment]
应该是，改了之后4倍内存。双1080ti应该刚好能跑64*64的casiab的训练。128*128的。。。显存也是4倍。我们没跑过128的，占显存太大了。

**Comment by cyummy** [comment]
了解了　非常感谢！
