### ISSUE TITLE
Training Error

### ISSUE THREAD

**Issue by akashsahu410** [AbnerHqC/GaitSet#57]
Initialzing...
Initializing data source...
Loading training data...
Data initialization complete.
Initializing model...
Model initialization complete.
Training START
Traceback (most recent call last):

  File "<ipython-input-1-0fc91df4d9dd>", line 1, in <module>
    runfile('C:/Users/HI/Downloads/Gait modules/GaitSet-master/train.py', wdir='C:/Users/HI/Downloads/Gait modules/GaitSet-master')

  File "C:\Users\HI\AppData\Local\conda\conda\envs\deblur\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 786, in runfile
    execfile(filename, namespace)

  File "C:\Users\HI\AppData\Local\conda\conda\envs\deblur\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/HI/Downloads/Gait modules/GaitSet-master/train.py", line 21, in <module>
    m.fit()

  File "C:\Users\HI\Downloads\Gait modules\GaitSet-master\model\model.py", line 151, in fit
    for seq, view, seq_type, label, batch_frame in train_loader:

  File "C:\Users\HI\AppData\Local\conda\conda\envs\deblur\lib\site-packages\torch\utils\data\dataloader.py", line 819, in __iter__
    return _DataLoaderIter(self)

  File "C:\Users\HI\AppData\Local\conda\conda\envs\deblur\lib\site-packages\torch\utils\data\dataloader.py", line 560, in __init__
    w.start()

  File "C:\Users\HI\AppData\Local\conda\conda\envs\deblur\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)

  File "C:\Users\HI\AppData\Local\conda\conda\envs\deblur\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)

  File "C:\Users\HI\AppData\Local\conda\conda\envs\deblur\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)

  File "C:\Users\HI\AppData\Local\conda\conda\envs\deblur\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)

  File "C:\Users\HI\AppData\Local\conda\conda\envs\deblur\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)

  File "C:\Users\HI\AppData\Local\conda\conda\envs\deblur\lib\site-packages\torch\multiprocessing\reductions.py", line 213, in reduce_tensor
    (device, handle, storage_size_bytes, storage_offset_bytes) = storage._share_cuda_()

RuntimeError: cuda runtime error (71) : operation not supported at c:\a\w\1\s\windows\pytorch\torch\csrc\generic\StorageSharing.cpp:232

ERROR: execution aborted

**Comment by akashsahu410** [comment]
Using python 3.7 with spyder.Getting above errors

**Comment by AbnerHqC** [comment]
Hi~Maybe you used an old version of PyTorch? This code is tested on PyTorch 0.4.

**Comment by 704856858** [comment]
i have the same question. my torch version is 1.0 ,but it is not work
