### ISSUE TITLE
train 训练出错

### ISSUE THREAD

**Issue by abjuration** [AbnerHqC/GaitSet#58]
您好，我在训练时出现这个错误，请问是什么原因导致的呢？
/home/wtu/anaconda3/envs/py/bin/python3.5 /home/wtu/1111111/GaitSet/GaitSet-master/train.py
Initialzing...
Initializing data source...
Loading training data...
Data initialization complete.
Initializing model...
Model initialization complete.
Training START
Traceback (most recent call last):
  File "/home/wtu/1111111/GaitSet/GaitSet-master/train.py", line 19, in <module>
    m.fit()
  File "/home/wtu/1111111/GaitSet/GaitSet-master/model/utils/modeltest.py", line 144, in fit
    num_workers=self.num_workers)
TypeError: __init__() got an unexpected keyword argument 'batch_sampler'

Process finished with exit code 1

**Comment by AbnerHqC** [comment]
应该是您自己写的modeltest.py有问题

**Comment by abjuration** [comment]
十分感谢您上次的解答，这次我确认model.py没有问题，运行train.py还是出现上次的问题，我用的pytorch是0.1.12版本，会不会是我pytorch版本的问题呢？
/home/wtu/anaconda3/envs/py/bin/python3.5 /home/wtu/1111111/GaitSet/GaitSet-master/train.py
Initialzing...
Initializing data source...
Loading training data...
Data initialization complete.
Initializing model...
Traceback (most recent call last):
Model initialization complete.
Training START
  File "/home/wtu/1111111/GaitSet/GaitSet-master/train.py", line 19, in <module>
    m.fit()
  File "/home/wtu/1111111/GaitSet/GaitSet-master/model/model.py", line 145, in fit
    num_workers=self.num_workers)
TypeError: __init__() got an unexpected keyword argument 'batch_sampler'

Process finished with exit code 1

**Comment by AbnerHqC** [comment]
有可能，代码是在pytorch0.4上调试的
