### ISSUE TITLE
预处理问题

### ISSUE THREAD

**Issue by blackzt** [AbnerHqC/GaitSet#64]
您好，请问在运行pretreatment.py代码时，为什么输出的根路径没有图片只有文件夹？然后运行时会出现：
File "C:\ProgramData\Anaconda3\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

**Comment by erhahaha** [comment]
我也遇到了，请问您解决了吗

**Comment by erhahaha** [comment]
QAQ  仍然木有解决，报错如下：

 0 <class 'NotADirectoryError'>
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "D:\anaconda\envs\tensorflow-gpu\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "E:\GaitSet\GaitSet-master\pretreatment.py", line 125, in cut_pickle
    frame_list = os.listdir(seq_path)
NotADirectoryError: [WinError 267] 目录名称无效。: 'E:\\GaitSet\\CASIA-B\\fyc\\00_1\\fyc-00_1-001.png'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pretreatment.py", line 194, in <module>
    raise e
  File "pretreatment.py", line 186, in <module>
    res.get(timeout=0.1)
  File "D:\anaconda\envs\tensorflow-gpu\lib\multiprocessing\pool.py", line 644, in get
    raise self._value
NotADirectoryError: [Errno 20] 目录名称无效。: 'E:\\GaitSet\\CASIA-B\\fyc\\00_1\\fyc-00_1-001.png'

**Comment by changfufu** [comment]
数据集的目录层数不对。input文件夹下，需要3层文件，第四层才是图片，也就是说在input设置的文件夹内，你需要再打开3次文件夹，才能看到图片

**Comment by CatbossMr** [comment]
我换了一份预处理代码，已经解决
https://blog.csdn.net/qq_21464351/article/details/109546421

**Comment by BoNiu-HZY** [comment]
同求解第一个问题
