### ISSUE TITLE
train报错QAQ

### ISSUE THREAD

**Issue by erhahaha** [AbnerHqC/GaitSet#65]
我在Windows10进行的调试，预处理之后，train报错如下（可能您在Linux上不会遇到这个问题，如果您了解这个问题，希望能得到您的答复，感谢！！）：
(tensorflow-gpu) E:\GaitSet\GaitSet-master>python train.py
Initialzing...
Initializing data source...
Loading training data...
Data initialization complete.
Initializing model...
Model initialization complete.
Training START
THCudaCheck FAIL file=c:\a\w\1\s\tmp_conda_3.6_104352\conda\conda-bld\pytorch_1550400396997\work\torch\csrc\generic\StorageSharing.cpp line=232 error=71 : operation not supported
Traceback (most recent call last):
  File "train.py", line 21, in <module>
    m.fit()
  File "E:\GaitSet\GaitSet-master\model\model.py", line 150, in fit
    for seq, view, seq_type, label, batch_frame in train_loader:
  File "D:\anaconda\envs\tensorflow-gpu\lib\site-packages\torch\utils\data\dataloader.py", line 819, in __iter__
    return _DataLoaderIter(self)
  File "D:\anaconda\envs\tensorflow-gpu\lib\site-packages\torch\utils\data\dataloader.py", line 560, in __init__
    w.start()
  File "D:\anaconda\envs\tensorflow-gpu\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "D:\anaconda\envs\tensorflow-gpu\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\anaconda\envs\tensorflow-gpu\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "D:\anaconda\envs\tensorflow-gpu\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "D:\anaconda\envs\tensorflow-gpu\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "D:\anaconda\envs\tensorflow-gpu\lib\site-packages\torch\multiprocessing\reductions.py", line 213, in reduce_tensor
    (device, handle, storage_size_bytes, storage_offset_bytes) = storage._share_cuda_()
RuntimeError: cuda runtime error (71) : operation not supported at c:\a\w\1\s\tmp_conda_3.6_104352\conda\conda-bld\pytorch_1550400396997\work\torch\csrc\generic\StorageSharing.cpp:232

(tensorflow-gpu) E:\GaitSet\GaitSet-master>Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\anaconda\envs\tensorflow-gpu\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "D:\anaconda\envs\tensorflow-gpu\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

**Comment by erhahaha** [comment]
[https://ptorch.com/news/166.html](url)
暂时解决啦，不知道后续还会不会出现其他问题。。。

**Comment by clay066** [comment]
您好,我在训练的时候也碰到了这个问题,请问您是怎么解决的?

**Comment by last-wish** [comment]
> 我在Windows10进行的调试，预处理之后，train报错如下（可能您在Linux上不会遇到这个问题，如果您了解这个问题，希望能得到您的答复，感谢！！）：
> (tensorflow-gpu) E:\GaitSet\GaitSet-master>python train.py
> Initialzing...
> Initializing data source...
> Loading training data...
> Data initialization complete.
> Initializing model...
> Model initialization complete.
> Training START
> THCudaCheck FAIL file=c:\a\w\1\s\tmp_conda_3.6_104352\conda\conda-bld\pytorch_1550400396997\work\torch\csrc\generic\StorageSharing.cpp line=232 error=71 : operation not supported
> Traceback (most recent call last):
> File "train.py", line 21, in
> m.fit()
> File "E:\GaitSet\GaitSet-master\model\model.py", line 150, in fit
> for seq, view, seq_type, label, batch_frame in train_loader:
> File "D:\anaconda\envs\tensorflow-gpu\lib\site-packages\torch\utils\data\dataloader.py", line 819, in **iter**
> return _DataLoaderIter(self)
> File "D:\anaconda\envs\tensorflow-gpu\lib\site-packages\torch\utils\data\dataloader.py", line 560, in **init**
> w.start()
> File "D:\anaconda\envs\tensorflow-gpu\lib\multiprocessing\process.py", line 105, in start
> self._popen = self._Popen(self)
> File "D:\anaconda\envs\tensorflow-gpu\lib\multiprocessing\context.py", line 223, in _Popen
> return _default_context.get_context().Process._Popen(process_obj)
> File "D:\anaconda\envs\tensorflow-gpu\lib\multiprocessing\context.py", line 322, in _Popen
> return Popen(process_obj)
> File "D:\anaconda\envs\tensorflow-gpu\lib\multiprocessing\popen_spawn_win32.py", line 65, in **init**
> reduction.dump(process_obj, to_child)
> File "D:\anaconda\envs\tensorflow-gpu\lib\multiprocessing\reduction.py", line 60, in dump
> ForkingPickler(file, protocol).dump(obj)
> File "D:\anaconda\envs\tensorflow-gpu\lib\site-packages\torch\multiprocessing\reductions.py", line 213, in reduce_tensor
> (device, handle, storage_size_bytes, storage_offset_bytes) = storage._share_cuda_()
> RuntimeError: cuda runtime error (71) : operation not supported at c:\a\w\1\s\tmp_conda_3.6_104352\conda\conda-bld\pytorch_1550400396997\work\torch\csrc\generic\StorageSharing.cpp:232
> 
> (tensorflow-gpu) E:\GaitSet\GaitSet-master>Traceback (most recent call last):
> File "", line 1, in
> File "D:\anaconda\envs\tensorflow-gpu\lib\multiprocessing\spawn.py", line 105, in spawn_main
> exitcode = _main(fd)
> File "D:\anaconda\envs\tensorflow-gpu\lib\multiprocessing\spawn.py", line 115, in _main
> self = reduction.pickle.load(from_parent)
> EOFError: Ran out of input

请问大佬是如何解决该问题的？
