### ISSUE TITLE
运行test.py遇到了value Error

### ISSUE THREAD

**Issue by zyfID** [AbnerHqC/GaitSet#80]
训练时迭代了5000次，然后pid_num=74，然后在运行test.py时出现了下面的错误：
```
Initialzing...
Initializing data source...
Data initialization complete.
Initializing model...
Model initialization complete.
Loading the model of iteration 5000...
Transforming...
Traceback (most recent call last):
  File "/home1/zhangyunfei/GaitSet-master/test.py", line 42, in <module>
    test = m.transform('test', opt.batch_size)
  File "/home1/zhangyunfei/GaitSet-master/model/model.py", line 253, in transform
    return np.concatenate(feature_list, 0), view_list, seq_type_list, label_list
ValueError: need at least one array to concatenate
```
我想问一下，想要运行test.py的话config.py中的哪些参数需要修改？然后还有就是train和test的数据集应该怎样划分，我按照论文里的ST MT LT来设置，但是也没成功。
麻烦作者大大帮我看看问题出在哪里，谢谢！

**Comment by cjx576** [comment]
我和您的问题一样，请问您的问题解决了吗？谢谢！

**Comment by CatbossMr** [comment]
你好，我也遇到了和你一样的问题，我解决了并已写成csdn博文
https://blog.csdn.net/qq_21464351/article/details/109546421
