### ISSUE TITLE
图片预处理问题

### ISSUE THREAD

**Issue by changfufu** [AbnerHqC/GaitSet#87]
我用的是CASIA-B数据集，在预处理图片时，提示以下信息
`
# JOB 1500 : --FINISH-- Contain 56 valid frames. Saved to /home/wcf/GaitSet-master/output/GaitDatasetC-silh/003/fb00.

ERROR OCCUR: PID ##%d##, ERRORTYPE: %s

 240 <class 'TypeError'>
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/wcf/anaconda3/envs/py36/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "pretreatment.py", line 130, in cut_pickle
    img = cv2.imread(frame_path)[:, :, 0]
TypeError: 'NoneType' object is not subscriptable
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pretreatment.py", line 194, in <module>
    raise e
  File "pretreatment.py", line 186, in <module>
    res.get(timeout=0.1)
  File "/home/wcf/anaconda3/envs/py36/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
TypeError: 'NoneType' object is not subscriptable
`
请问这是什么问题？如果忽略不计，会对训练模型产生什么影响？
非常感谢

**Comment by AbnerHqC** [comment]
你好，看起来是某个样本没读到
